FROM python:3.11-buster as builder

RUN pip install poetry
ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1

WORKDIR /code

COPY pyproject.toml poetry.lock ./
COPY query ./query

RUN poetry install --without dev --no-root

# The runtime image, used to just run the code provided its virtual environment
FROM python:3.11-slim-buster as runtime

WORKDIR /code

ENV VIRTUAL_ENV=/code/.venv \
    PATH="/code/.venv/bin:$PATH"

COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

COPY query ./query

CMD ["uvicorn", "query.main:app", "--host", "0.0.0.0", "--port", "5513"]