# This is the base hba config file
# On deployment you should create a similar file adding also your configs
# And point to it using POSTGRES_HBA_FILE in .env
#
# include file created by initdb. Note in the hba conf this must not be enclosed in quotes
include_if_exists /var/lib/postgresql/data/pg_hba.conf

