# This is the base PostgreSQL config file
# On deployment you should create a similar file adding also your configs
# And point to it using POSTGRES_CONFIG_FILE in .env

# include file created by initdb. Note in the main conf this must be enclosed in quotes
include_if_exists '/var/lib/postgresql/data/postgresql.conf'

# we have a specific hba file. Note this is the file name as seen from the PostgreSQL container
# as defined in the volume mapping in docker-compose.yml
hba_file='/etc/pg_hba.conf'
# Above was copied from base.conf

# Add replication settings for the primary database
wal_level=replica
max_wal_senders=3

# We don't set a large wal_keep_size because we will use slots
max_slot_wal_keep_size=20GB
max_slot_wal_keep_size=30GB
