
services:
  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    restart: ${RESTART_POLICY:-always}
    environment:
      DATA_SOURCE_URI: postgresql://${DOCKER_POSTGRES_ALIAS}:5432/?sslmode=disable
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}
    ports:
      -  ${POSTGRES_EXPORTER_EXPOSE:-127.0.0.1:5514}:9187
    networks:
      - common_net
